default_install_hook_types:
    - pre-commit
    - commit-msg
default_stages:
    - pre-commit

repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            language: node
            additional_dependencies:
                - '@trivago/prettier-plugin-sort-imports@^5.0.0'
                - prettier@^3.4.2
                - prettier-plugin-sort-json@^4.1.1
                - prettier-plugin-tailwindcss@^0.6.9

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.36.0
      hooks:
          - id: eslint
            language: node
            types: [file]
            types_or: [javascript, jsx, ts, tsx]
            additional_dependencies:
                - eslint@^9.15.0
                - eslint-import-resolver-typescript@^4.0.0
                - eslint-plugin-import@^2.31.0
                - eslint-plugin-jsx-a11y@^6.10.2
                - eslint-plugin-react@^7.37.2
                - eslint-plugin-react-hooks@^5.1.0
                - typescript-eslint@^8.16.0

    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.23.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            language: node
            additional_dependencies:
                - '@commitlint/cli@^19.6.1'
                - '@commitlint/config-conventional@^19.6.0'
